name: Run Postman API Tests (GoRest)

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Create dir
      run: |
        mkdir TestArtifact

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Newman (Postman CLI)
      run: |
        npm install -g newman
        npm install -g newman-reporter-slackreporter
        npm install -g newman-reporter-htmlextra

    - name: Run GoRest Postman Tests
      run: |
        newman run gorest_collection.json -e gorest_environment.json --reporters cli,htmlextra --reporter-htmlextra-export testArtifacts/htmlreport.html

    - name: Output HTML Report
      uses: actions/upload-artifact@v4
      with:
        name: Reports
        path: testArtifacts